services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: privello
    ports:
      - "5432:5432"
    volumes:
      - privello_pg:/var/lib/postgresql/data

volumes:
  privello_pg: